### ISSUE TITLE
Enchance the UI of application

### ISSUE THREAD

**Issue by salonishah01** [salonishah01/CSC510-FALL23-P28-Project3#1]
We need to work on the UI of the application to improve user experience and provide a visually appealing design.

**Comment by romil2807** [comment]
The bug has been fixed in this commit. 
Our application is now optimized for various screen sizes and devices, ensuring a seamless experience for users on desktops, tablets, and mobile devices. We've implemented a consistent color palette, fonts, and spacing to create a cohesive and professional look throughout the application.
